<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 60cc711a3682df16113ad72ff3473a48ff483d1e
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
<<<<<<< HEAD
=======
=======
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: "Strider — Football Stat Tracker",
  description: "Real-time football stat tracker for your weekly club",
};
>>>>>>> 8a1e020285740ea9b846db4a6d7605f8a22a47a7
>>>>>>> 60cc711a3682df16113ad72ff3473a48ff483d1e

export default function RootLayout({
  children,
}: {
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 60cc711a3682df16113ad72ff3473a48ff483d1e
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
<<<<<<< HEAD
=======
=======
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} font-body antialiased`}>
        {children}
      </body>
    </html>
  );
>>>>>>> 8a1e020285740ea9b846db4a6d7605f8a22a47a7
>>>>>>> 60cc711a3682df16113ad72ff3473a48ff483d1e
}
