<<<<<<< HEAD
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
=======
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: "Strider — Football Stat Tracker",
  description: "Real-time football stat tracker for your weekly club",
};
>>>>>>> 8a1e020285740ea9b846db4a6d7605f8a22a47a7

export default function RootLayout({
  children,
}: {
<<<<<<< HEAD
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
=======
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} font-body antialiased`}>
        {children}
      </body>
    </html>
  );
>>>>>>> 8a1e020285740ea9b846db4a6d7605f8a22a47a7
}
